export const ACHIEVEMENT_TEMPLATES = [
  {
    slug: "first-game",
    title: "First Steps",
    description: "Play your first game",
    criteria_type: "games_played",
    criteria_value: 1,
    reward_coins: 15,
    reward_xp: 10,
    icon: "Rocket",
  },
  {
    slug: "first-win",
    title: "First Win",
    description: "Win your first game",
    criteria_type: "games_won",
    criteria_value: 1,
    reward_coins: 20,
    reward_xp: 10,
    icon: "Trophy",
  },
  {
    slug: "coins-100",
    title: "Century Club",
    description: "Earn 100 coins in total",
    criteria_type: "coins_earned",
    criteria_value: 100,
    reward_coins: 25,
    reward_xp: 15,
    icon: "Coins",
  },
  {
    slug: "coins-1000",
    title: "Coin Collector",
    description: "Earn 1,000 coins in total",
    criteria_type: "coins_earned",
    criteria_value: 1000,
    reward_coins: 100,
    reward_xp: 50,
    icon: "CircleDollarSign",
  },
  {
    slug: "streak-7",
    title: "Weekly Warrior",
    description: "Keep a 7-day login streak",
    criteria_type: "streak_days",
    criteria_value: 7,
    reward_coins: 75,
    reward_xp: 40,
    icon: "Flame",
  },
  {
    slug: "streak-30",
    title: "Monthly Legend",
    description: "Keep a 30-day login streak",
    criteria_type: "streak_days",
    criteria_value: 30,
    reward_coins: 250,
    reward_xp: 120,
    icon: "Crown",
  },
  {
    slug: "games-50",
    title: "Game Enthusiast",
    description: "Play 50 games",
    criteria_type: "games_played",
    criteria_value: 50,
    reward_coins: 120,
    reward_xp: 60,
    icon: "Gamepad2",
  },
  {
    slug: "challenges-100",
    title: "Challenge Master",
    description: "Complete 100 challenges",
    criteria_type: "challenges_completed",
    criteria_value: 100,
    reward_coins: 200,
    reward_xp: 100,
    icon: "Flag",
  },
  {
    slug: "referral-master",
    title: "Social Butterfly",
    description: "Refer 5 friends",
    criteria_type: "referrals",
    criteria_value: 5,
    reward_coins: 150,
    reward_xp: 75,
    icon: "Users",
  },
  {
    slug: "scratch-10",
    title: "Scratch Champion",
    description: "Scratch 10 cards",
    criteria_type: "scratch_cards",
    criteria_value: 10,
    reward_coins: 80,
    reward_xp: 40,
    icon: "Ticket",
  },
  {
    slug: "math-10",
    title: "Numbers Wizard",
    description: "Complete 10 math challenges",
    criteria_type: "math_challenges",
    criteria_value: 10,
    reward_coins: 90,
    reward_xp: 45,
    icon: "Calculator",
  },
  {
    slug: "level-5",
    title: "Rising Star",
    description: "Reach level 5",
    criteria_type: "level_reached",
    criteria_value: 5,
    reward_coins: 100,
    reward_xp: 50,
    icon: "Star",
  },
];