export const MISSION_TEMPLATES = [
  {
    slug: "play-3-games",
    title: "Game On!",
    description: "Play 3 games",
    type: "play_games",
    target: 3,
    reward_coins: 25,
    reward_xp: 15,
    icon: "Gamepad2",
    is_daily: true,
  },
  {
    slug: "win-2-games",
    title: "Winning Streak",
    description: "Score above the threshold in 1 game",
    type: "win_games",
    target: 1,
    reward_coins: 35,
    reward_xp: 20,
    icon: "Trophy",
    is_daily: true,
  },
  {
    slug: "complete-challenge",
    title: "Challenge Accepted",
    description: "Complete 1 challenge",
    type: "complete_challenges",
    target: 1,
    reward_coins: 30,
    reward_xp: 15,
    icon: "Flag",
    is_daily: true,
  },
  {
    slug: "math-master",
    title: "Math Master",
    description: "Complete a math challenge",
    type: "math_challenge",
    target: 1,
    reward_coins: 30,
    reward_xp: 15,
    icon: "Calculator",
    is_daily: true,
  },
  {
    slug: "scratch-day",
    title: "Scratch That",
    description: "Scratch a card today",
    type: "scratch_cards",
    target: 1,
    reward_coins: 20,
    reward_xp: 10,
    icon: "Ticket",
    is_daily: true,
  },
  {
    slug: "login-week",
    title: "7-Day Streak",
    description: "Maintain a 7-day login streak",
    type: "streak_days",
    target: 7,
    reward_coins: 100,
    reward_xp: 50,
    icon: "Flame",
    is_daily: false,
  },
  {
    slug: "invite-friends",
    title: "Invite Friends",
    description: "Refer 1 friend to CoinQuest",
    type: "referrals",
    target: 1,
    reward_coins: 75,
    reward_xp: 30,
    icon: "Users",
    is_daily: false,
  },
  {
    slug: "earn-500",
    title: "Coin Collector",
    description: "Earn 500 coins in total",
    type: "earn_coins",
    target: 500,
    reward_coins: 60,
    reward_xp: 25,
    icon: "Coins",
    is_daily: false,
  },
];